### ISSUE TITLE
Failed to start in CS:GO

### ISSUE THREAD

**Issue by bman46** [SilentSys/SLAM#123]
When I click on the start button in slam it shows up with the following error:
`System.UnauthorizedAccessException: Access to the path 'C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\csgo\cfg\slam.cfg' is denied.`

It was able to start and play music a week or two ago, and when I opened the folder that it failed at, I tried to create the slam.cfg file and it did not let me (with admin privilege), however I instead was able to create a file named lam.cfg, so maybe valve blocked it?

Logs:
`System.UnauthorizedAccessException: Access to the path 'C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\csgo\cfg\slam.cfg' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path)
   at SLAM.Form1.CreateCfgFiles(SourceGame Game, String SteamappsPath)
   at SLAM.Form1.PollRelayWorker_DoWork(Object sender, DoWorkEventArgs e)`

**Comment by bman46** [comment]
restarted my computer and now it works for some reason.
Closed #123
