### ISSUE TITLE
YouTube Import Issues

### ISSUE THREAD

**Issue by HDFlood** [SilentSys/SLAM#131]
Having a bit of difficulties loading YouTube imports into SLAM. I've had this issue only recently.  The consistent error seems to be __YoutubeExtractor.YoutubeParseException__. Examples:

```
--------------------18/11/2018 06:18:44 UTC--------------------
YoutubeExtractor.YoutubeParseException: Could not parse the Youtube page for URL http://youtube.com/watch?v=VnWEMCvlHck
This may be due to a change of the Youtube page structure.
Please report this bug at www.github.com/flagbug/YoutubeExtractor/issues ---> System.NotSupportedException: Result cannot be called on a failed Match.
   at System.Text.RegularExpressions.Match.Result(String replacement)
   at YoutubeExtractor.DownloadUrlResolver.GetHtml5PlayerVersion(JObject json)
   at YoutubeExtractor.DownloadUrlResolver.GetDownloadUrls(String videoUrl, Boolean decryptSignature)
   --- End of inner exception stack trace ---
   at YoutubeExtractor.DownloadUrlResolver.ThrowYoutubeParseException(Exception innerException, String videoUrl)
   at YoutubeExtractor.DownloadUrlResolver.GetDownloadUrls(String videoUrl, Boolean decryptSignature)
   at SLAM.YTImport.DownloadWorker_DoWork(Object sender, DoWorkEventArgs e)
```

```
--------------------18/11/2018 06:24:16 UTC--------------------
YoutubeExtractor.YoutubeParseException: Could not parse the Youtube page for URL http://youtube.com/watch?v=N8nGig78lNs
This may be due to a change of the Youtube page structure.
Please report this bug at www.github.com/flagbug/YoutubeExtractor/issues ---> System.NotSupportedException: Result cannot be called on a failed Match.
   at System.Text.RegularExpressions.Match.Result(String replacement)
   at YoutubeExtractor.DownloadUrlResolver.GetHtml5PlayerVersion(JObject json)
   at YoutubeExtractor.DownloadUrlResolver.GetDownloadUrls(String videoUrl, Boolean decryptSignature)
   --- End of inner exception stack trace ---
   at YoutubeExtractor.DownloadUrlResolver.ThrowYoutubeParseException(Exception innerException, String videoUrl)
   at YoutubeExtractor.DownloadUrlResolver.GetDownloadUrls(String videoUrl, Boolean decryptSignature)
   at SLAM.YTImport.DownloadWorker_DoWork(Object sender, DoWorkEventArgs e)
```

There hasn't been any resolutions on the [main issue page](https://www.github.com/flagbug/YoutubeExtractor/issues), so I wanted to forward it here to see if anyone has the same issue and/or can help. Any redirects would also help. ~~(I'm also expecting this to get closed cuz it tech doesn't belong here lol)~~

**Comment by Korveen** [comment]
+ same problem

**Comment by mendelgusmao** [comment]
YouTube is making it hard to download content with 3rd party apps and from time to time it's expected some of them will fail. NewPipe on Android is a good example of an app that needs to be updated when YouTube breaks the downloads.

The real issue is not within SLAM, but [YoutubeExtractor](github.com/flagbug/YoutubeExtractor), the lib SLAM uses to provide this feature.

**Comment by a6d6061ed1** [comment]
> 
> 
> YouTube is making it hard to download content with 3rd party apps and from time to time it's expected some of them will fail. NewPipe on Android is a good example of an app that needs to be updated when YouTube breaks the downloads.
> 
> The real issue is not within SLAM, but [YoutubeExtractor](github.com/flagbug/YoutubeExtractor), the lib SLAM uses to provide this feature.

this is easily fixed with changes to Decipherer.cs, just look in issues on YoutubeExtractor page and you'll find it
