### ISSUE TITLE
Slam wont play sounds anymore

### ISSUE THREAD

**Issue by Zalavis** [SilentSys/SLAM#52]
Problem started when I was using slam earlier today, whenever I try selecting another audio file in console, it played the same sound I had previously. (Even though it said the new sound was selected)

Now it has gotten even worse, now when I try to play sounds, not a single sound plays. Whenever I hit the keybind to play the sounds, my microphone just echoes the people talking in the game. I have no clue how to fix this, any ideas?

Error log
--------------------7/31/2016 1:15:43 AM--------------------
System.IO.IOException: The process cannot access the file 'D:\Steam\steamapps\common\Counter-Strike Global Offensive\voice_input.wav' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at NAudio.Wave.WaveFileWriter..ctor(String filename, WaveFormat format)
   at NAudio.Wave.WaveFileWriter.CreateWaveFile(String filename, IWaveProvider sourceProvider)
   at SLAM.Form1.LoadTrack(SourceGame Game, Int32 index, String SteamappsPath)

--------------------7/31/2016 2:02:01 AM--------------------
System.NullReferenceException: Object reference not set to an instance of an object.
   at SLAM.Form1.GetFilepath(String ProcessName)
   at SLAM.Form1.PollRelayWorker_DoWork(Object sender, DoWorkEventArgs e)

**Comment by Zalavis** [comment]
I see getting help on this forum is useless considering no one has been helped since early april.
