### ISSUE TITLE
conversion complete! however, the following files failed to convert: XXXX 

### ISSUE THREAD

**Issue by meodaiduoi** [SilentSys/SLAM#79]
--------------------4/30/2017 11:53:58 AM UTC--------------------
System.Runtime.InteropServices.COMException (0xC00D36C4): Exception from HRESULT: 0xC00D36C4
   at NAudio.MediaFoundation.MediaFoundationInterop.MFCreateSourceReaderFromURL(String pwszURL, IMFAttributes pAttributes, IMFSourceReader& ppSourceReader)
   at NAudio.Wave.MediaFoundationReader.CreateReader(MediaFoundationReaderSettings settings)
   at NAudio.Wave.MediaFoundationReader..ctor(String file, MediaFoundationReaderSettings settings)
   at NAudio.Wave.MediaFoundationReader..ctor(String file)
   at SLAM.Form1.WaveCreator(String File, String outputFile, SourceGame Game)
   at SLAM.Form1.WavWorker_DoWork(Object sender, DoWorkEventArgs e)
--------------------4/30/2017 11:54:24 AM UTC--------------------
System.Runtime.InteropServices.COMException (0xC00D36C4): Exception from HRESULT: 0xC00D36C4
   at NAudio.MediaFoundation.MediaFoundationInterop.MFCreateSourceReaderFromURL(String pwszURL, IMFAttributes pAttributes, IMFSourceReader& ppSourceReader)
   at NAudio.Wave.MediaFoundationReader.CreateReader(MediaFoundationReaderSettings settings)
   at NAudio.Wave.MediaFoundationReader..ctor(String file, MediaFoundationReaderSettings settings)
   at NAudio.Wave.MediaFoundationReader..ctor(String file)
   at SLAM.Form1.WaveCreator(String File, String outputFile, SourceGame Game)
   at SLAM.Form1.WavWorker_DoWork(Object sender, DoWorkEventArgs e)
--------------------4/30/2017 11:55:34 AM UTC--------------------
System.Runtime.InteropServices.COMException (0xC00D36C4): Exception from HRESULT: 0xC00D36C4
   at NAudio.MediaFoundation.MediaFoundationInterop.MFCreateSourceReaderFromURL(String pwszURL, IMFAttributes pAttributes, IMFSourceReader& ppSourceReader)
   at NAudio.Wave.MediaFoundationReader.CreateReader(MediaFoundationReaderSettings settings)
   at NAudio.Wave.MediaFoundationReader..ctor(String file, MediaFoundationReaderSettings settings)
   at NAudio.Wave.MediaFoundationReader..ctor(String file)
   at SLAM.Form1.WaveCreator(String File, String outputFile, SourceGame Game)
   at SLAM.Form1.WavWorker_DoWork(Object sender, DoWorkEventArgs e)
--------------------4/30/2017 11:59:03 AM UTC--------------------
System.Runtime.InteropServices.COMException (0xC00D36C4): Exception from HRESULT: 0xC00D36C4
   at NAudio.MediaFoundation.MediaFoundationInterop.MFCreateSourceReaderFromURL(String pwszURL, IMFAttributes pAttributes, IMFSourceReader& ppSourceReader)
   at NAudio.Wave.MediaFoundationReader.CreateReader(MediaFoundationReaderSettings settings)
   at NAudio.Wave.MediaFoundationReader..ctor(String file, MediaFoundationReaderSettings settings)
   at NAudio.Wave.MediaFoundationReader..ctor(String file)
   at SLAM.Form1.WaveCreator(String File, String outputFile, SourceGame Game)
   at SLAM.Form1.WavWorker_DoWork(Object sender, DoWorkEventArgs e)

**Comment by SilentSys** [comment]
This issue should be fixed in [v1.5.1](https://github.com/SilentSys/SLAM/tree/v1.5.1), please update SLAM and open a new issue if it persists.
